name: C/C++ CI

on:
  push:
    branches:
      - test*
  pull_request:

jobs:
  build:

    #runs-on: ubuntu-latest

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]


    steps:
    - uses: actions/checkout@v4
    #- run: sudo apt-get -y install yodl build-essential
    
    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y yodl build-essential libgdbm-dev
        
    - if: runner.os == 'macOS'
      run: |
        brew install autoconf gdbm # ncurses pcre2

    - name: configure
      run: |
        ./Util/preconfig
        ./configure --enable-zsh-debug --enable-zsh-mem-debug --enable-zsh-mem-warning --enable-zsh-secure-free --enable-zsh-heap-debug --enable-zsh-hash-debug --enable-pcre --enable-multibyte # --enable-cap --enable-gdbm
        cat config.h
    - name: make
      run: make
    - name: test
      run: TERM=xterm make check
    # - name: make check
    #   run: TERM=xterm make check

